### ISSUE TITLE
Crashlytics init failed

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#20]
07-02 14:54:48.050 3045-3063/com.hashcube.sqmtest I/FlurryAgent: New main file also not found. returning..
07-02 14:54:48.050 3045-3076/com.hashcube.sqmtest W/ResourceType: No package identifier when getting value for resource number 0x00000000
07-02 14:54:48.055 3045-3076/com.hashcube.sqmtest E/Fabric: Could not calculate hash for app icon.
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.Resources.getValue(Resources.java:2558)
        at android.content.res.Resources.openRawResource(Resources.java:2472)
        at android.content.res.Resources.openRawResource(Resources.java:2448)
        at io.fabric.sdk.android.services.common.CommonUtils.getAppIconHashOrNull(CommonUtils.java:812)
        at io.fabric.sdk.android.services.settings.Settings.initialize(Settings.java:83)
        at io.fabric.sdk.android.Onboarding.retrieveSettingsData(Onboarding.java:124)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:99)
        at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:45)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
        at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
        at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
07-02 14:54:48.065 3045-3045/com.hashcube.sqmtest E/CrashlyticsCore: .
    .     |  | 
    .     |  |
    .     |  |
    .   \ |  | /
    .    \    /
    .     \  /
    .      \/
    .
    This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
    install an Android build tool and ask a team member to invite you to this app's organization.
    .
    .      /\
    .     /  \
    .    /    \
    .   / |  | \
    .     |  |
    .     |  |
    .     |  |
    .
07-02 14:54:48.065 3045-3045/com.hashcube.sqmtest E/JS: {plugins} WARNING: Unknown event could not be delivered for plugin: any , method: onCreate 
07-02 14:54:48.070 3045-3045/com.hashcube.sqmtest E/JS: {billing} Installing listener

**Comment by CodeCombiner** [comment]
I need to log in in order this app to become visible but I need to login to organization. The best solution if you invite me to your organization and then grant access to com.hashcube.sqmtest app to me.

**Comment by rampr** [comment]
This is done, please check if you now have access

**Comment by rampr** [comment]
According to https://stackoverflow.com/a/48904968/123132 looks like a launcher icon issue.
I'm thinking fixing #19 would solve this issue

**Comment by rampr** [comment]
Saw this error message
                    Crashlytics was applied to an android-library project.
                    Android-library support is currently an incubating feature.
                    Contact support@fabric.io with any issues.
Was going through the stackoverflow article about this warning https://stackoverflow.com/questions/23991988/android-studio-0-5-9-2-annoying-gradle-warnings

I'm wondering if the crashytics issues is because of this.

**Comment by CodeCombiner** [comment]
Fixed and pushed

**Comment by rampr** [comment]
Closing.
