### ISSUE TITLE
Error in firebase

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#21]
07-02 15:28:41.700 4855-5656/com.hashcube.sqmtest W/FirebasePerformance: getResultUrl throws exception
    java.lang.IllegalArgumentException: Illegal character in path at index 32: https://graph.facebook.com/v2.3/ 1404706263104694
        at java.net.URI.create(URI.java:733)
        at com.google.android.gms.internal.firebase-perf.zzl.zzd(Unknown Source)
        at com.google.android.gms.internal.firebase-perf.zzl.zzn(Unknown Source)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
07-02 15:28:41.700 4855-5656/com.hashcube.sqmtest I/FirebasePerformance: URL cannot be parsed
    Unable to process an HTTP request/response due to missing or invalid values. See earlier log statements for additional information on the specific invalid/missing values.
07-02 15:28:56.230 4855-5059/com.hashcube.sqmtest I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by rampr** [comment]
This seems to be just an issue with the performance sdk, If that is removed, then I think the error would go away

**Comment by rampr** [comment]
I looked at the issue more closely, looks like there is a space at index 32 and that could be the issue.

**java.lang.IllegalArgumentException: Illegal character in path at index 32: https://graph.facebook.com/v2.3/ 1404706263104694**

**Comment by CodeCombiner** [comment]
Removed empty space in manifest.xsl for parameters insertion

**Comment by rampr** [comment]
This is also fixed
