### ISSUE TITLE
Code signing fails for release builds

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#32]
```
                   124 actionable tasks: 124 executed
         [android]  Signing APK at /Users/rampr/work/hashcube/sudoku-quest-mobile/build/release/native-android/bin
       [jarsigner]  jarsigner -sigalg MD5withRSA -digestalg SHA1 -keystore /Users/rampr/.android/hashcube.keystore -storepass ****** -keypass ***** -signedjar sqmtest-unaligned.apk sqmtest-release-unsigned.apk hashcube
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn jarsigner ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by CodeCombiner** [comment]
Done

**Comment by rampr** [comment]
This now works, but the build doesn't run and gets stuck at the splash screen. I've created #36.
Closing this.
