### ISSUE TITLE
Game doesn't go past splash screen in release builds, debug build works though

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#36]
Attaching the log:
[release.log](https://github.com/CodeCombiner/native-android/files/2187489/release.log)

Relevant sections from the log
```
07-12 11:40:00.089 878-1041/? I/JS: {js} Reporting exception
    http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/dom/sax.js line: 1
07-12 11:40:00.094 878-1041/? I/JS: 218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]/,nameChar=RegExp("[\
    SyntaxError: Invalid regular expression: /[\-\.0-9A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD????-??\ux203F-???]/: Range out of order in character class
        at new RegExp (<anonymous>)
        at RegExp (<anonymous>)
        at Object.$$_sax (http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/dom/sax.js:1:5952)
        at I (none:615:5092)
        at z (none:615:6690)
        at Object.jsio (none:615:7357)
        at Object.$$_dom_parser (http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/dom/dom_parser.js:1:3511)
        at I (none:615:5092)
        at z (none:615:6690)
        at Object.jsio (none:615:7357)
        at Object.$$_dom_DOMParser (http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/dom/DOMParser.js:1:66)
        at I (none:615:5092)
        at z (none:615:6690)
        at Object.jsio (none:615:7357)
        at Object.$$_common.exports.install (http://com.hashcube.sqtest/modules/devkit-core/src/clientapi
07-12 11:40:00.164 878-996/? I/JS: {js} Reporting exception
    http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/plugins.js line: 1
    ta)}),NATIVE.events.registerHandler("pluginEvent",function(u){var s=GC.plugins
    ReferenceError: GC is not defined
        at http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/plugins.js:1:621
        at $$_events.NATIVE.events.dispatchEvent (http://com.hashcube.sqtest/modules/devkit-core/src/clientapi/native/events.js:1:601)
07-12 11:40:00.179 878-894/? D/FirebaseInstanceId: topic sync succeeded
```

**Comment by CodeCombiner** [comment]
Can we test it again?

**Comment by rampr** [comment]
I tested it again. Still happens

**Comment by rampr** [comment]
Was happening because of one or all of these environment variables

LC_ALL=C
LC_CTYPE=C
LANG=C
