### ISSUE TITLE
Error during build of whack that mole

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#37]
I was trying out a simple example of building another project -> https://github.com/hashcube/whack-that-mole

The build completes, but during the build, I see the following error and the the game doesn't run.

Logs during build:

```
Unhandled rejection Error: ENOENT: no such file or directory, scandir '/Users/rampr/work/hashcube/whack-that-mole/build/whackthatmole/tealeaf/libs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at /Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/build.js:624:30
    at tryCatcher (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/rampr/work/hashcube/whack-that-mole/modules/devkit-core/modules/native-android/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
       [ndk-build]  ndk-build NDK_PROJECT_PATH=tealeaf/src/main
```

Logs when running:
```
07-12 14:55:16.424 30020-30071/com.lilvarmit.whackthatmole I/JS: {js} Initial setup took 14ms
    {CAT} CLEARING ALL TIMERS
07-12 14:55:16.429 30020-30071/com.lilvarmit.whackthatmole I/JS: {debugger} JavaScript Debug Server running on port 9222
07-12 14:55:16.429 30020-30075/com.lilvarmit.whackthatmole I/v8: Failed to open socket on port 9222, waiting 1000 ms before retrying
07-12 14:55:16.434 30020-30071/com.lilvarmit.whackthatmole I/JS: {js} Initialized in 12ms
07-12 14:55:16.519 30020-30071/com.lilvarmit.whackthatmole D/JS: http://s.wee.cat:80/
07-12 14:55:16.534 30020-30071/com.lilvarmit.whackthatmole I/JS: {core} Evaluated JavaScript from native.js
07-12 14:55:16.549 30020-30071/com.lilvarmit.whackthatmole D/JS: 12 Jul 14:55:16 
    Error loading module:
         [[ import gc.native.launchClient; ]]
         requested by: ./<initial file> 
         current directory: http://s.wee.cat:80/ 
       Error: Could not import `gc.native.launchClient`
      	looked in:
      		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient.js
      		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient/index.js
      		http://s.wee.cat:80/gc/native/launchClient.js
      		http://s.wee.cat:80/gc/native/launchClient/index.js
      		http://s.wee.cat:80/lib/gc/native/launchClient.js
      		http://s.wee.cat:80/lib/gc/native/launchClient/index.js
      		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient.js
      		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient/index.js
      		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient.js
      		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient/index.js
      	Import Stack:
      		
        at loadModule (none:1286:17)
        at _require (none:1442:34)
          at none:675:27
          at none:1:1
07-12 14:55:16.549 30020-30071/com.lilvarmit.whackthatmole I/JS: {js} Reporting exception
    none line: 1465
              throw err;
    Error: Could not import `gc.native.launchClient`
    	looked in:
    		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient.js
    		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient/index.js
    		http://s.wee.cat:80/gc/native/launchClient.js
    		http://s.wee.cat:80/gc/native/launchClient/index.js
    		http://s.wee.cat:80/lib/gc/native/launchClient.js
    		http://s.wee.cat:80/lib/gc/native/launchClient/index.js
    		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient.js
    		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient/index.js
    		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient.js
    		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient/index.js
    	Import Stack:
    		
        at loadModule (none:1286:17)
        at _require (none:1442:34)
        at none:675:27
        at none:1:1
07-12 14:55:16.909 30020-30043/com.lilvarmit.whackthatmole I/JS: {js} WARNING: Queued an event because the JavaScript code does not hook events
07-12 14:55:16.919 30020-30043/com.lilvarmit.whackthatmole I/JS: {canvas} Resizing screen to (1080, 1920)
07-12 14:55:16.929 30020-30043/com.lilvarmit.whackthatmole I/JS: {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
07-12 14:55:16.929 30020-30043/com.lilvar
```

**Comment by rampr** [comment]
The same happens when trying `devkit init mygame` and trying to compile

**Comment by CodeCombiner** [comment]
Seems What the mole uses hashcube devkit-core because I can see it in git config:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://github.com/gameclosure/devkit-core
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[submodule "modules/native-android"]
	url = https://github.com/gameclosure/native-android
[submodule "modules/native-ios"]
	url = https://github.com/gameclosure/native-ios
[submodule "modules/squill"]
	url = https://github.com/gameclosure/squill
[submodule "modules/timestep"]
	url = https://github.com/gameclosure/timestep
[submodule "node_modules/jsio"]
	url = https://github.com/gameclosure/js.io
```

**Comment by rampr** [comment]
I changed it to use your native-android repo and that's when it fails.
You can also try doing devkit init newgame and same issues happens

**Comment by CodeCombiner** [comment]
Fixed
