### ISSUE TITLE
Variable or codeHost is undefined - Build doesn't break, Game stuck at splash screen

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#43]
Seeing this error when building. Build doesn't fail though. But game doesn't run

```
[xslt]  [error]  ERROR:  'line 115: Variable or parameter 'codeHost' is undefined.'
                    [error]  FATAL ERROR:  'line 115: Variable or parameter 'codeHost' is undefined.'

                    [error]             :line 115: Variable or parameter 'codeHost' is undefined.

                    [error]  javax.xml.transform.TransformerConfigurationException: line 115: Variable or parameter 'codeHost' is undefined.

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:988)

                    [error]  	at com.gameclosure.tealeaf.tools.XsltTool.transformXSL(XsltTool.java:69)

                    [error]  	at com.gameclosure.tealeaf.tools.XsltTool.exec(XsltTool.java:51)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools$Tool.run(TealeafBuildTools.java:183)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools$ToolServer.serve(TealeafBuildTools.java:108)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools$ToolServer.serveForever(TealeafBuildTools.java:63)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools.main(TealeafBuildTools.java:36)

                    [error]  Caused by: line 115: Variable or parameter 'codeHost' is undefined.

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.UnresolvedRef.typeCheck(UnresolvedRef.java:90)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.AttributeValueTemplate.typeCheck(AttributeValueTemplate.java:212)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.LiteralAttribute.typeCheck(LiteralAttribute.java:68)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.LiteralElement.typeCheck(LiteralElement.java:190)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:484)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:291)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:484)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:654)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:405)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:469)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:554)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:947)

                    [error]  	... 6 more

                    [error]  ---------

                    [error]  line 115: Variable or parameter 'codeHost' is undefined.

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.UnresolvedRef.typeCheck(UnresolvedRef.java:90)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.AttributeValueTemplate.typeCheck(AttributeValueTemplate.java:212)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.LiteralAttribute.typeCheck(LiteralAttribute.java:68)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.LiteralElement.typeCheck(LiteralElement.java:190)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:484)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:291)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:484)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:654)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:405)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:469)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:554)

                    [error]  	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:947)

                    [error]  	at com.gameclosure.tealeaf.tools.XsltTool.transformXSL(XsltTool.java:69)

                    [error]  	at com.gameclosure.tealeaf.tools.XsltTool.exec(XsltTool.java:51)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools$Tool.run(TealeafBuildTools.java:183)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools$ToolServer.serve(TealeafBuildTools.java:108)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools$ToolServer.serveForever(TealeafBuildTools.java:63)

                    [error]  	at com.gameclosure.tealeaf.TealeafBuildTools.main(TealeafBuildTools.java:36)
```

**Comment by rampr** [comment]
When running the game see the following issue
```

07-18 06:49:07.941 16416-16583/com.hashcube.sqmtest I/JS: {debugger} JavaScript Debug Server running on port 9222
07-18 06:49:07.951 16416-16583/com.hashcube.sqmtest I/JS: {js} Initialized in 22ms
07-18 06:49:08.276 16416-16583/com.hashcube.sqmtest I/JSDEBUG: {jsdebug} GC took 3ms (Mark/Sweep/Compact)
07-18 06:49:08.411 16416-16583/com.hashcube.sqmtest D/JS: http://s.wee.cat:80/
07-18 06:49:08.426 16416-16583/com.hashcube.sqmtest I/JS: {core} Evaluated JavaScript from native.js
07-18 06:49:08.426 16416-16532/com.hashcube.sqmtest I/JS: {js} WARNING: Queued an event because the JavaScript code does not hook events
07-18 06:49:08.451 16416-16583/com.hashcube.sqmtest D/JS: 18 Jul 06:49:08 
    Error loading module:
         [[ import gc.native.launchClient; ]]
         requested by: ./<initial file> 
         current directory: http://s.wee.cat:80/ 
       Error: Could not import `gc.native.launchClient`
      	looked in:
      		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient.js
      		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient/index.js
      		http://s.wee.cat:80/gc/native/launchClient.js
      		http://s.wee.cat:80/gc/native/launchClient/index.js
      		http://s.wee.cat:80/lib/gc/native/launchClient.js
      		http://s.wee.cat:80/lib/gc/native/launchClient/index.js
      		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient.js
      		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient/index.js
      		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient.js
      		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient/index.js
      	Import Stack:
      		
        at loadModule (none:1286:17)
        at _require (none:1442:34)
          at none:675:27
          at none:1:1
07-18 06:49:08.451 16416-16583/com.hashcube.sqmtest I/JS: {js} Reporting exception
    none line: 1465
              throw err;
    Error: Could not import `gc.native.launchClient`
    	looked in:
    		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient.js
    		http://s.wee.cat:80/modules/devkit-core/node_modules/jsio/packages/gc/native/launchClient/index.js
    		http://s.wee.cat:80/gc/native/launchClient.js
    		http://s.wee.cat:80/gc/native/launchClient/index.js
    		http://s.wee.cat:80/lib/gc/native/launchClient.js
    		http://s.wee.cat:80/lib/gc/native/launchClient/index.js
    		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient.js
    		http://s.wee.cat:80/modules/devkit-core/src/clientapi/api/gc/native/launchClient/index.js
    		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient.js
    		http://s.wee.cat:80/modules/devkit-core/modules/timestep/src/gc/native/launchClient/index.js
    	Import Stack:
    		
        at loadModule (none:1286:17)
        at _require (none:1442:34)
        at none:675:27
        at none:1:1
07-18 06:49:08.461 16416-16532/com.hashcube.sqmtest I/JS: {canvas} Resizing screen to (1080, 1920)
07-18 06:49:08.466 16416-16532/com.hashcube.sqmtest I/JS: {js} WARNING: Queued an event because the JavaScript code does not hook events
07-18 06:49:08.471 16416-16532/com.hashcube.sqmtest I/JS: {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
    {js} WARNING: Queued an event because the JavaScript code does not hook events
```

**Comment by rampr** [comment]
Removing the code changes for codeHost allows the build to not throw those errors and the game runs too.

**Comment by rampr** [comment]
This is a blocker, temporarily I have removed the code changes regarding commenting of codeHost and moved forward

**Comment by rampr** [comment]
This is now resolved
