### ISSUE TITLE
Game crashes on receiving a push notification

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#49]
Relevant logs

```
07-23 18:36:50.832 3349-3349/? E/JS: {{OnesignalPlugin}} Notification received 
07-23 18:36:50.832 4570-4570/? W/ResourcesManager: getTopLevelResources: /data/app/com.hashcube.sqmtest-1/base.apk / 1.0 running in com.android.systemui rsrc of package null
07-23 18:36:50.842 3349-3462/? D/JS: 23 Jul 18:36:50 LOG console LOG onesignal {onesignal} data at js {"failed":false,"notification_data":"{\"notification_id\":\"fbeac410-31a6-4ca0-99b6-3a792a9618ea\",\"is_foreground\":true,\"title\":\"Test\",\"body\":\"Test\"}","name":"onesignalNotificationReceived","priority":0}
07-23 18:36:50.852 4075-5340/? V/BroadcastQueue: [background] Process cur broadcast BroadcastRecord{2eef0e9 u0 com.google.android.c2dm.intent.RECEIVE qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{23a3ac4 3349:com.hashcube.sqmtest/u0a1665}
07-23 18:36:50.872 4570-4570/? W/ResourcesManager: getTopLevelResources: /data/app/com.hashcube.sqmtest-1/base.apk / 1.0 running in com.android.systemui rsrc of package null
07-23 18:36:50.887 3349-3349/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>
    Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.messaging.RemoteMessage>
07-23 18:36:50.892 3349-3857/? W/System.err: java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)"
07-23 18:36:50.897 3349-3857/? W/System.err:     at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
07-23 18:36:50.907 4570-4570/? D/KnoxNotification: ----- inflateViews : modified publicViewLocal -----
07-23 18:36:50.912 4570-4570/? W/ResourcesManager: getTopLevelResources: /data/app/com.hashcube.sqmtest-1/base.apk / 1.0 running in com.android.systemui rsrc of package null
07-23 18:36:50.922 4570-4570/? D/KnoxNotification: ----- inflateViews : modified KnoxViewLocal -----
07-23 18:36:50.922 4570-4570/? W/ResourcesManager: getTopLevelResources: /data/app/com.hashcube.sqmtest-1/base.apk / 1.0 running in com.android.systemui rsrc of package null
07-23 18:36:50.932 4570-4570/? D/PanelView: kidsfalse mQsExpansionEnabled:true
07-23 18:36:50.942 4570-4570/? D/PanelView: kidsfalse mQsExpansionEnabled:true
07-23 18:36:51.137 3349-3405/? W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.hashcube.sqmtest/files/.YFlurrySenderIndex.info.AnalyticsMain
07-23 18:36:51.147 3349-3859/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
07-23 18:36:51.147 3675-4433/? D/EnterpriseController: netId is 0
07-23 18:36:51.147 3675-4433/? D/Netd: getNetworkForDns: using netid 508 for uid 11665
07-23 18:36:51.252 3349-3857/? E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebaseMessagingService
    Process: com.hashcube.sqmtest, PID: 3349
    java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)"
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
07-23 18:36:51.257 3349-3403/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
07-23 18:36:51.257 4075-5353/? W/ActivityManager:   Force finishing activity com.hashcube.sqmtest/.sqmtestActivity
07-23 18:36:51.257 3675-4433/? D/EnterpriseController: netId is 0
07-23 18:36:51.257 3675-4433/? D/Netd: getNetworkForDns: using netid 508 for uid 11665
07-23 18:36:51.257 4075-5353/? D/FocusedStackFrame: Set to : 0
07-23 18:36:51.262 4075-4285/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{ec53db9 u0 d0 com.sec.android.app.launcher/com.android.launcher2.Launcher}
07-23 18:36:51.262 4570-4570/? D/PhoneStatusBar: setSystemUiVisibility vis=8500 mask=ffffffff oldVal=9706 newVal=8500 diff=1206
07-23 18:36:51.272 4866-4866/? D/WallpaperService: MSG_WINDOW_RESIZED
    updateSurface
07-23 18:36:51.272 4866-4866/? V/WallpaperService: Changes: creating=false format=false size=false
    mWidth:1920 SurfaceWidth:1920 mHeight:1920 SurfaceHeigh:1920
07-23 18:36:51.272 4075-5353/? D/InputDispatcher: Focus left window: 3349
    Focus entered window: 4940
07-23 18:36:51.272 4075-4328/? D/PointerIcon: setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:4075 uid:1000
    setMouseCustomIcon IconType is same.101
    setHoveringSpenIconStyle1 pointerType: 10001 iconType:1 flag:0 pid:4075 uid:1000
    setHoveringSpenCustomIcon IconType is same.1
07-23 18:36:51.277 3349-3349/? E/JS: {focus} Lost focus 
07-23 18:36:51.282 4075-4604/? D/InputMethodManagerService: windowGainedFocus mCurrentFocusedUserId - 0 and mSecureKeypadEnabled-false
07-23 18:36:51.287 4866-4866/? V/WallpaperService: Wallpaper size has changed: (1920, 1920)
07-23 18:36:51.287 4075-4285/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{ec53db9 u0 d0 com.sec.android.app.launcher/com.android.launcher2.Launcher}
07-23 18:36:51.287 4570-4570/? D/PhoneStatusBar: setSystemUiVisibility vis=40008500 mask=ffffffff oldVal=8500 newVal=40008500 diff=40000000
07-23 18:36:51.287 4075-5353/? D/InputDispatcher: Focused application set to: xxxx
07-23 18:36:51.297 4570-4570/? D/BatteryMeterView: onDraw batteryColor : -1107296257
07-23 18:36:51.352 14940-14940/? D/SamsungIME: onStartInput: No inputType, No imeOption, isInputViewShown = false, isExtractViewShown = false, isShowInputRequested = false, isConfigChanged = false
07-23 18:36:51.387 4075-3861/? W/DropBoxManagerService: Dropping: data_app_crash (607 > 0 bytes)
07-23 18:36:51.397 3349-3349/? E/JS: {tealeaf} Activity got onPause 
07-23 18:36:51.402 4075-5324/? I/Sensors: Acc old sensor_state 1, new sensor_state : 0 en : 0
07-23 18:36:51.417 3349-3349/? D/SensorManager: unregisterListener ::   
07-23 18:36:51.422 3349-3349/? I/AmazonInsightsSDK: Session Paused.
07-23 18:36:51.422 3349-3349/? V/AmazonInsightsSDK: Firing Session Event: _session.pause
07-23 18:36:51.422 4075-3865/? E/android.os.Debug: ro.product_ship = true
    ro.debug_level = 0x4f4c
    sys.mobilecare.preload = false

```

**Comment by CodeCombiner** [comment]
Fixed

**Comment by rampr** [comment]
great. will test it out and close this

**Comment by rampr** [comment]
Works
